[package]
name = "node-prune"
version = "0.1.0"
authors = ["makeco <lidongjies@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.4.0"
log = "0.4.8"
walkdir = "2.2.9"
